## Numpy 

Numpy: Abreviación para Numerical Python, es usado para trabajar con vectores y matrices.


In [5]:
# Se debe importar la libreria para usar numpy
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[-1])
print(arr[3])

[1 2 3 4]
1
4
4


In [6]:
# Accediendo a elementos de un array
arr = np.array([1,2,3,4])
print(arr[0]+arr[3])

5


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 
print(arr[4:]) 
print(arr[:4]) 
print(max(arr))

[2 3 4 5]
[5 6 7]
[1 2 3 4]
7


In [8]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
c = np.ones(10)
print(c)

In [ ]:
# Crear un array desde 2 hasta 10 con 5 elementos
lin_a = np.linspace(1,10,5) 
print(lin_a)

In [ ]:
range_a = np.arange(5)
print(range_a)

In [ ]:
A = np.eye(3)
print(A)
B = np.array([[1,2],[2,4]])
print(B)

In [ ]:
a = np.arange(10)
b = np.arange(10,20)
print(a)
print(b) 

In [ ]:
print(a+b)

In [ ]:
print(a*b)

In [ ]:
print(a)
print(a + 2)

In [ ]:
print(a@b)

### Tipos de datos en numpy

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype) 
print(type(arr))
print(type(arr[0]))

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

In [ ]:
## Copiando arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

In [ ]:
# Dimensiones de un array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr) 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

newarr = arr.reshape(-1)

print(newarr) 

In [ ]:
# usando for en arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x) 

In [ ]:
# Uniendo dos arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

In [ ]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr) 

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

In [ ]:
# Dividir arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

In [ ]:
# Busqueda con arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

In [ ]:
#Encuentre las posiciones donde los valores sean pares
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

In [ ]:
# Ordenando arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

In [ ]:
# Filtrado de datos
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) 

In [ ]:
# Filtrado de datos

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) 

In [ ]:
from skimage import io
imagen = io.imread("placa_petri.jpeg")
print(imagen)

In [ ]:
print(imagen.shape)

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(imagen)

In [ ]:
plt.imshow(imagen[::-1])

In [ ]:
imagen2 = np.where(imagen > 100,255,0)
plt.imshow(imagen2)

### Resolviendo ecuaciones 
$$ a+b = 10$$
$$ a-b = 5$$

$$ M\cdot X= R $$

 $$\begin{bmatrix} 
    1 & 1 \\
    1 &-1
    \end{bmatrix} \begin{bmatrix} a \\ b \end{bmatrix} = \begin{bmatrix} 10 \\ 5 \end{bmatrix}$$

In [ ]:
M = np.array([1, 1, 1, -1])
M = M.reshape(2,2)
R = np.array([10,5])
X = np.linalg.solve(M,R)
print(X)

In [ ]:
M_inv = np.linalg.inv(M)
print(M_inv)

In [ ]:
X = np.matmul(M_inv,R)
print(X)